"Name: \PR:/1WDA/C5STANDARD==============CP\TY:CL_TOOLBAR_DROPDOWN_BY_KEY\SE:PUBLIC\SE:END\EI
ENHANCEMENT 0 ZE_WD_DD_SH_C5.
* WD DropDown with SearchHelp
    DATA zmo_sh TYPE REF TO /1wda/dtable_cell_editor.

ENDENHANCEMENT.
